=== adityagoel26/open-source-connectors/officialboomi-workday-prism-2ab4eea77f19/src/main/resources/schema/create_bucket_input.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "name",
    "targetDataset",
    "operation",
    "schema"
  ],
  "properties": {
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "bucket11"
      ],
      "pattern": "^(.*)$"
    },
    "targetDataset": {
      "$id": "#/properties/targetDataset",
      "type": "object",
      "title": "The Targetdataset Schema",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/targetDataset/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": [
            "624651067bd601696f5b2deabe1e6605"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "operation": {
      "$id": "#/properties/operation",
      "type": "object",
      "title": "The Operation Schema",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/operation/properties/id",
          "type": "string",
          "title": "The Id Schema",
          "default": "",
          "examples": [
            "Operation_Type=Replace"
          ],
          "pattern": "^(.*)$"
        }
      }
    },
    "schema": {
      "$id": "#/properties/schema",
      "type": "object",
      "title": "The Schema Schema",
      "required": [
        "parseOptions",
        "fields",
        "schemaVersion"
      ],
      "properties": {
        "parseOptions": {
          "$id": "#/properties/schema/properties/parseOptions",
          "type": "object",
          "title": "The Parseoptions Schema",
          "required": [
            "fieldsDelimitedBy",
            "fieldsEnclosedBy",
            "headerLinesToIgnore",
            "charset",
            "type"
          ],
          "properties": {
            "fieldsDelimitedBy": {
              "$id": "#/properties/schema/properties/parseOptions/properties/fieldsDelimitedBy",
              "type": "string",
              "title": "The Fieldsdelimitedby Schema",
              "default": "",
              "examples": [
                ","
              ],
              "pattern": "^(.*)$"
            },
            "fieldsEnclosedBy": {
              "$id": "#/properties/schema/properties/parseOptions/properties/fieldsEnclosedBy",
              "type": "string",
              "title": "The Fieldsenclosedby Schema",
              "default": "",
              "examples": [
                "\""
              ],
              "pattern": "^(.*)$"
            },
            "headerLinesToIgnore": {
              "$id": "#/properties/schema/properties/parseOptions/properties/headerLinesToIgnore",
              "type": "integer",
              "title": "The Headerlinestoignore Schema",
              "default": 0,
              "examples": [
                1
              ]
            },
            "charset": {
              "$id": "#/properties/schema/properties/parseOptions/properties/charset",
              "type": "object",
              "title": "The Charset Schema",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "$id": "#/properties/schema/properties/parseOptions/properties/charset/properties/id",
                  "type": "string",
                  "title": "The Id Schema",
                  "default": "",
                  "examples": [
                    "Encoding=UTF-8"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            },
            "type": {
              "$id": "#/properties/schema/properties/parseOptions/properties/type",
              "type": "object",
              "title": "The Type Schema",
              "required": [
                "id"
              ],
              "properties": {
                "id": {
                  "$id": "#/properties/schema/properties/parseOptions/properties/type/properties/id",
                  "type": "string",
                  "title": "The Id Schema",
                  "default": "",
                  "examples": [
                    "Schema_File_Type=Delimited"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          }
        },
        "fields": {
          "$id": "#/properties/schema/properties/fields",
          "type": "array",
          "title": "The Fields Schema",
          "items": {
            "$id": "#/properties/schema/properties/fields/items",
            "type": "object",
            "title": "The Items Schema",
            "required": [
              "ordinal",
              "name",
              "description",
              "precision",
              "scale",
              "type"
            ],
            "properties": {
              "ordinal": {
                "$id": "#/properties/schema/properties/fields/items/properties/ordinal",
                "type": "integer",
                "title": "The Ordinal Schema",
                "default": 0,
                "examples": [
                  1
                ]
              },
              "name": {
                "$id": "#/properties/schema/properties/fields/items/properties/name",
                "type": "string",
                "title": "The Name Schema",
                "default": "",
                "examples": [
                  "Employee"
                ],
                "pattern": "^(.*)$"
              },
              "description": {
                "$id": "#/properties/schema/properties/fields/items/properties/description",
                "type": "string",
                "title": "The Description Schema",
                "default": "",
                "examples": [
                  "Employee"
                ],
                "pattern": "^(.*)$"
              },
              "precision": {
                "$id": "#/properties/schema/properties/fields/items/properties/precision",
                "type": "integer",
                "title": "The Precision Schema",
                "default": 0,
                "examples": [
                  255
                ]
              },
              "scale": {
                "$id": "#/properties/schema/properties/fields/items/properties/scale",
                "type": "integer",
                "title": "The Scale Schema",
                "default": 0,
                "examples": [
                  0
                ]
              },
              "type": {
                "$id": "#/properties/schema/properties/fields/items/properties/type",
                "type": "object",
                "title": "The Type Schema",
                "required": [
                  "id",
                  "descriptor"
                ],
                "properties": {
                  "id": {
                    "$id": "#/properties/schema/properties/fields/items/properties/type/properties/id",
                    "type": "string",
                    "title": "The Id Schema",
                    "default": "",
                    "examples": [
                      "fdd7dd26156610006a12d4fd1ea300ce"
                    ],
                    "pattern": "^(.*)$"
                  },
                  "descriptor": {
                    "$id": "#/properties/schema/properties/fields/items/properties/type/properties/descriptor",
                    "type": "string",
                    "title": "The Descriptor Schema",
                    "default": "",
                    "examples": [
                      "Text"
                    ],
                    "pattern": "^(.*)$"
                  }
                }
              }
            }
          }
        },
        "schemaVersion": {
          "$id": "#/properties/schema/properties/schemaVersion",
          "type": "object",
          "title": "The Schemaversion Schema",
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "$id": "#/properties/schema/properties/schemaVersion/properties/id",
              "type": "string",
              "title": "The Id Schema",
              "default": "",
              "examples": [
                "Schema_Version=1.0"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      }
    }
  }
}

=== adityagoel26/open-source-connectors/officialboomi-workday-prism-2ab4eea77f19/src/test/resources/create_bucket.json
{
    "name": "Bucket_for_tabe_98221ced868f015585263b17254c014d0564",
    "targetDataset": {
        "id": "98221ced868f015585263b1721014d09"
    },
    "operation": {
        "id": "Operation_Type=Replace"
    },
    "schema": {
        "parseOptions": {
            "fieldsDelimitedBy": ",",
            "fieldsEnclosedBy": "\"",
            "headerLinesToIgnore": 1,
            "charset": {
                "id": "Encoding=UTF-8"
            },
            "type": {
                "id": "Schema_File_Type=Delimited"
            }
        },
        "fields": [
            {
                "ordinal": 1,
                "name": "Employee",
                "description": "Employee",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 2,
                "name": "Employee_ID",
                "description": "Employee ID",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 3,
                "name": "Job_Title",
                "description": "Job Title",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 4,
                "name": "Supervisory_Organization",
                "description": "Supervisory Organization",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 5,
                "name": "Supervisory_Organization_ID",
                "description": "Supervisory Organization - ID",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 6,
                "name": "Manager",
                "description": "Manager",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 7,
                "name": "Business_Site",
                "description": "Business Site",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 8,
                "name": "Annual_Salary",
                "description": "Annual Salary",
                "precision": 18,
                "scale": 2,
                "type": {
                    "id": "32e3fa0dd9ea1000072bac410415127a",
                    "descriptor": "Numeric"
                }
            },
            {
                "ordinal": 9,
                "name": "Salary_Currency",
                "description": "Salary Currency",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            },
            {
                "ordinal": 10,
                "name": "Last_Performance_Rating",
                "description": "Last Performance Rating",
                "precision": 255,
                "scale": 0,
                "type": {
                    "id": "fdd7dd26156610006a12d4fd1ea300ce",
                    "descriptor": "Text"
                }
            }
        ],
        "schemaVersion": {
            "id": "Schema_Version=1.0"
        }
    }
}
